### ISSUE TITLE
Great job

### ISSUE THREAD

**Issue by Globik** [versatica/mediasoup-demo#1]
Thank you very much.

**Comment by ibc** [comment]
thanks

**Comment by Globik** [comment]
Firefox does not work.
In Chromium does not work statistics. Version 57.

**Comment by ibc** [comment]
Hi, I'm sorry but I cannot also handle issue reports on this demo. It's just a demo. 
BTW Firefox does work. If you find a specific bug please report it in the mediasoup project.
