### ISSUE TITLE
Error: Cannot find module './lib/Logger'

### ISSUE THREAD

**Issue by Rennos** [versatica/mediasoup-demo#12]
Rename './lib/Logger' to './lib/logger'.

**Comment by ibc** [comment]
Where? Please provide the full trace.

**Comment by Rennos** [comment]
In server.js
```javascript
const Logger = require('./lib/Logger')
```

**Comment by ibc** [comment]
Thanks, it was a problem with OSX filesystem which is case insensitive. Fixed now in master
