### ISSUE TITLE
Constantly says connecting

### ISSUE THREAD

**Issue by AdamMiltonBarker** [versatica/mediasoup-demo#13]
Hi guys, got everything set up and all seems ok, however in the access url it constantly says connecting and does not connect, in the UI it shows no connected browsers. Any suggestions?

**Comment by ibc** [comment]
If your server has a private IP (AWS, Google Cloud Engine, Azure, etc), you must redirect the public IP to it, and must set `rtcAnnounceIPv4` in the mediasoup Server settings:

https://mediasoup.org/documentation/mediasoup/api/#Server-ServerSettings
