### ISSUE TITLE
Camera flipping doesn't work in mobile chrome (Android)

### ISSUE THREAD

**Issue by thehappycoder** [versatica/mediasoup-demo#16]
I noticed that mediasoup-demo has the same issue. The solution is to stop the tracks both on mediaStream and videoProducer:

Typescript example:
```
export const switchCamera = async (
  videoDevicesCycle: Iterator<MediaDeviceInfo>,
  videoStream: MediaStream,
  videoProducer: any
): Promise<MediaStream> => {
  const videoDevice = videoDevicesCycle.next().value

  videoStream!.getVideoTracks()[0].stop()
  videoProducer.track.stop()

  videoStream = await getStream(
    config.videoMediaStreamConstraints(videoDevice!.deviceId)
  )

  await videoProducer.replaceTrack(videoStream.getVideoTracks()[0])

  return videoStream
}
```

**Comment by ibc** [comment]
This should not work. When the `track` handled by a `Producer` is stopped, the `Producer` gets closed:

https://github.com/versatica/mediasoup-client/blob/master/lib/Producer.js#L575

I may change that if needed and just emit the "trackended" event in the `Producer`, but I just wonder how the above code can work for you.

**Comment by thehappycoder** [comment]
Oh, yeah, interesting. I am not sure why, but it works on both Android and iOS Safari. I could do `track.onended = null` for now just in case.

Other peers see a short video pause that gets replaced by a different track in 1-2 seconds.

**Comment by ibc** [comment]
Could you add listeners to the "close" and "trackended" events in the video Producer, log something into them, and check whether they are called or not with your code above?

Also, when a Producer is closed you should get a "notify" event in your local `Room` instance (since mediasoup-client must tell the server about the Producer closure).

**Comment by ibc** [comment]
BTW could you please move this issue to https://github.com/versatica/mediasoup-client/issues?
This is just a demo app.

**Comment by thehappycoder** [comment]
Sure. Will do it when I get to the office.

**Comment by ibc** [comment]
Thanks. Take your time. I just want to have it in order to document the problem since I don't think the mediasoup-client library can, by itself, run your code when detecting that the mobile orientation changes.

**Comment by thehappycoder** [comment]
```
console.log('Creating trackended and close event handlers')

  videoProducer.on('trackended', () => {
    console.log('!!!!!!!!!!!!!!!!!', 'trackended')
  })

  videoProducer.on('close', () => {
    console.log('!!!!!!!!!!!!!!!!!', 'close')
  })
```

Got `Creating trackended and close event handlers` but didn't get the other console logs.

I think this https://bugs.chromium.org/p/chromium/issues/detail?id=752913 explains why it happens.
