### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by MrMoronIV** [versatica/mediasoup-demo#20]
If I follow the installation steps it throws all kinds of errors while running npm install in the server folder:

npm ERR! git clone --template=/home/XXXXX/.npm/_git-remotes/_templates --mirror git://github.com/gulpjs/gulp.git /home/XXXXX/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-ecf98f08: Cloning into bare repository '/home/XXXXX/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-ecf98f08'...
npm ERR! git clone --template=/home/XXXXX/.npm/_git-remotes/_templates --mirror git://github.com/gulpjs/gulp.git /home/XXXXX/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-ecf98f08:
npm ERR! git clone --template=/home/XXXXX/.npm/_git-remotes/_templates --mirror git://github.com/gulpjs/gulp.git /home/XXXXX/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-ecf98f08: fatal: unable to connect to github.com:
npm ERR! git clone --template=/home/XXXXX/.npm/_git-remotes/_templates --mirror git://github.com/gulpjs/gulp.git /home/XXXXX/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-ecf98f08: github.com[0: 192.30.253.113]: errno=No route to host
npm ERR! git clone --template=/home/XXXXX/.npm/_git-remotes/_templates --mirror git://github.com/gulpjs/gulp.git /home/XXXXX/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-ecf98f08: github.com[1: 192.30.253.112]: errno=No route to host
npm ERR! Linux 2.6.32-042stab123.9
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10
npm ERR! code 128

npm ERR! Command failed: git clone --template=/home/XXXXX/.npm/_git-remotes/_templates --mirror git://github.com/gulpjs/gulp.git /home/XXXXX/.npm/_git-remotes/git-github-com-gulpjs-gulp-git-4-0-ecf98f08
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.253.113]: errno=No route to host
npm ERR! github.com[1: 192.30.253.112]: errno=No route to host

any suggestions?

**Comment by ibc** [comment]
GitHub was down.

**Comment by MrMoronIV** [comment]
yeah that's just nonsense, just tried it again, same result, thanks for closing this though wow

**Comment by ibc** [comment]
"No route to host". Try replacing the gulp entry in package.json with "^4.0.0".

**Comment by MrMoronIV** [comment]
that seems to give a better result, this also means the current release of mediasoup-demo is not installable without this change.

I also made the exact same change in the app folder... This is what the app installation gives me at the very start

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by MrMoronIV** [comment]
So this thing only works in the root of a domain?
Why would one use only absolute paths?

**Comment by ibc** [comment]
I've been to install, both the app and the server, right now following the steps in README.

Anyway: please, consider this just a demo and not a full application. It's intended for showing a basic mediasoup client+server usage, nothing else. If you plan to use mediasoup you are supposed to build your own client+server app by following the official mediasoup and mediasoup-client API documentation.
