### ISSUE TITLE
MS Edge not working

### ISSUE THREAD

**Issue by harris** [versatica/mediasoup-demo#24]
Repro: 
1. open up https://demo.mediasoup.org in MS Edge 
2. open another browser on MS Edge.  

The video does not send over.  On a side note, Chrome video is able to receive Edge browser's video but Edge does not receive chrome's video.

**Comment by ibc** [comment]
Unfortunately I don't have a Windows machine so cannot test Edge. Will do eventually but cannot say when.

Anyway, this is just a demo. I don't want issues here. If you set up your own mediasoup application and find an issue (like no video in Edge) please ask in the mailing list by providing much more info (which video codec, etc).
