### ISSUE TITLE
Invalid SSL cert date

### ISSUE THREAD

**Issue by akilude** [versatica/mediasoup-demo#27]
Hi,

The demo is not working due to an invalid SSL cert, this is most likely due to the node js process running the demo referencing the expired LetsEncrypt Certificate in memory rather than the new one. Restarting the nodejs process should force it to use the current certificate.

![image](https://user-images.githubusercontent.com/19281798/40473239-4582c688-5f59-11e8-9de8-6e82b4f88bb3.png)

**Comment by ibc** [comment]
Thanks, done.
