### ISSUE TITLE
Demo server refusing connections

### ISSUE THREAD

**Issue by kkar** [versatica/mediasoup-demo#28]
Hello, I have set up mediasoup demo and exposed the public directory in NGINX's config. I can see the whole app, the problem is that the websocket cannot connect (I have pasted the error below). The domain is SSL enabled (Let's Encrypt) and the port is listening as well. Any help, please?

`VM304:164 WebSocket connection to 'wss://conference.think-free.net:3443/?peerName=lsgmk1y2&roomId=dacglu88' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

**Comment by ibc** [comment]
No idea, sorry, check your iptables rules.
