### ISSUE TITLE
Input/output settings menu

### ISSUE THREAD

**Issue by mdempsky** [versatica/mediasoup-demo#29]
Google Meet supports selecting between multiple video/audio sources and multiple audio sinks. I think it would be useful if the mediasoup-demo app supported this functionality too.

**Comment by ibc** [comment]
This is just a demo, not a production ready application. You can do whatever you wish with mediasoup.

**Comment by mdempsky** [comment]
Understood that I can do whatever I wish on my own. However, the demo app seems complete enough as-is for my production use cases, and I thought that others would benefit from having source/sink selection.

If I implement that functionality, is it worth sending a Pull Request or do you intentionally want to keep the demo app minimal?

Thanks.

**Comment by ibc** [comment]
Thanks, but I prefer to keep it minimal. The mediasoup-demo does not aim to be a full-featured application.
