### ISSUE TITLE
Cannot find module 'mediasoup

### ISSUE THREAD

**Issue by shahulinfo6** [versatica/mediasoup-demo#32]
i followed all steps successfully here(https://github.com/versatica/mediasoup-demo)but after that when i 
type $ cd server
        $ node server.js

It displays the following in command:

E:\New folder\mediasoup-demo-master\server>node server.js
- process.env.DEBUG: undefined
- config.mediasoup.logLevel: warn
- config.mediasoup.logTags: [ 'info', 'ice', 'dtls', 'rtp', 'srtp', 'rtcp', 'rbe
', 'rtx' ]
module.js:549
    throw err;
    ^

Error: Cannot find module 'mediasoup'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (E:\New folder\mediasoup-demo-master\server\server.js:
19:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

and my browser console displays as the following:
debug.js:122 mediasoup-demo:ERROR:RoomClient restartIce() failed: InvalidStateError: invalid state "new"
    at Room.restartIce (https://XXX.XXX.X:3000/mediasoup-demo-app.js:12857:28)
    at https://192.168.1.22:3000/mediasoup-demo-app.js:601:18 +1s
debug @ debug.js:122

when i type $ gulp live it listening port successfully and opened automatically in browser but it blinking connecting but it doesn't open camera.
Please help me how to solve this issue?

**Comment by ibc** [comment]
NPM INSTALL

**Comment by shahulinfo6** [comment]
yes i installed (npm install) but still the above same error occurs but another terminal (gulp live)running successfully and the browser opening automatically and listening port into my local system..

but i configured into live server and enabled port ,added ssl certificate but when i run node server.js it displays the same error above and when i run gulp live into live server it displays the following error 
root@master:/usr/lib/node_modules/video_conferencing_vc/app# gulp live 
        /usr/lib/node_modules/video_conferencing_vc/app/gulpfile.js:65
        let bundler = browserify(
        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at execute (/usr/lib/node_modules/gulp-cli/lib/versioned/^4.0.0/index.js:36:18)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp-cli/index.js:175:63)
    at Liftoff.execute (/usr/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:203:12)

**Comment by ibc** [comment]
You need Node >= 6.0 in your host.

**Comment by shahulinfo6** [comment]
thank you for your response.its working.
it listening  External: https://xxxxxxxxx.com:3000 
but my browser console displays Error as following:
browser.js:20 WebSocket connection to 'wss://xxxxxxxxx.com:3443/?peerName=tqyqeydq&roomId=jaimvi65' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

may i know where i need to change port i changed the following port only
 httpsServer.listen(3443, '0.0.0.0', () =>

when i run (gulp live):
And it displays  as the following:

[Browsersync] Couldn't open browser (if you are using BrowserSync in a headless environment, you might want to set the open option to false)

when i (node server.js):
And it displays as the following:

 root@webinar:/usr/lib/server# node server.js
- process.env.DEBUG: undefined
- config.mediasoup.logLevel: warn
- config.mediasoup.logTags: [ 'info', 'ice', 'dtls', 'rtp', 'srtp', 'rtcp', 'rbe', 'rtx' ]
[opening Readline Command Console...]

**Comment by shahulinfo6** [comment]
I installed successfully but it blinks connecting for few seconds after that displays closed.Camera cannot open.It listening port 3000 ( https://xxxxxxxxx.com:3000) on browser but when i saw console it lstening port  wss://:xxxxxxxxx.com:3443.. i changed into mediasoup-demo-app file 3443 as 3000 but when i run node server.js and gulp live it automatically changed into 3443 again .i dont know how to run .Please help me how to solve this issue?

**Comment by ibc** [comment]
I'm sorry but I don't provide support for the mediasoup demo app. It's just a demo.

**Comment by shahulinfo6** [comment]
Oh, It's ok. Sorry to disturbed.
