### ISSUE TITLE
ICE failed, add a STUN server and see about:webrtc for more details

### ISSUE THREAD

**Issue by 654129588** [versatica/mediasoup-demo#33]
I set up the client according to the document, and the local environment can complete video communication, but I found this error when I deployed to the cloud server And no data traffic is generated.

ICE failed, add a STUN server and see about:webrtc for more details

What's going on here?

**Comment by ibc** [comment]
Redirect and open your ports in your server (if needed), check whether your server has public or private IP (if so map it in the mediasoup Server config), etc.

The demo application is not "production ready" and cannot be just deployed in any server. Reading the mediasoup API documentation is required.

**Comment by ibc** [comment]
Feel free to ask in the mailing list about this question. I want to keep usage questions there in the mailing list rather than in GitHub issues. Thanks.
