### ISSUE TITLE
npm install mediasoup not working

### ISSUE THREAD

**Issue by vishaljain790** [versatica/mediasoup-demo#34]
I have to install mediasoup on local environment(mac). But when i am installing it requires all the requirements like python(that i have on mac), but make, g++ are not available.
How can i resolve this?

**Comment by ibc** [comment]
Sorry, no idea about Heroku. Also, yes, `g++` is obviously required. I just don't believe that you cannot install `g++` in Heroku.

Anyway, this is the mediasoup demo project. No support is provided for the demo app, sorry.
