### ISSUE TITLE
config.js

### ISSUE THREAD

**Issue by thanatos19808** [versatica/mediasoup-demo#35]
I'm setting up the mediasoup-demo inside an aws amazon server with ubuntu 16.04, I can not receive the video or audio of the other connections. I have tried several configurations of the config.js file if I succeed. Could you provide me with an example of how a config.js should be viewed mounted on a server?

<a href="http://subefotos.com/ver/?82a592b11b4b1b4c0e192cf4edc7d13eo.png" target="_blank"><img src="http://thumbs.subefotos.com/82a592b11b4b1b4c0e192cf4edc7d13eo.jpg" /></a>

**Comment by ibc** [comment]
Please, use the mailing list for questions (this is not the mailing list). Also, please take into account what you have already been replied in Twitter regarding your AWS private IP, port ranges, and mediasoup settings.

**Comment by thanatos19808** [comment]
what is the  mailling list?
