### ISSUE TITLE
unable to run $ node server.js and app

### ISSUE THREAD

**Issue by kul1010** [versatica/mediasoup-demo#4]
I have changed version using nvm. But below error when used $ node server.js and $ gulp prod is working now.

pankaj@ubuntu:/var/www/mediasoup-demo/server$ node server.js

    process.env.DEBUG: LOG WARN ERROR mediasoup-worker
    config.mediasoup.logLevel: debug
    config.mediasoup.logTags: [ 'info', 'rtp', 'rtcp', 'rtx' ]
    [opening Readline Command Console...]
    cmd> mediasoup-demo-server:LOG protoo WebSocket server running +0ms
    mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +4ms
    mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +7ms
    mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +1ms
    mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
    mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
    mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
    mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
    mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +1ms
    mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
    mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
    mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
    mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +0ms
    mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +5ms
    mediasoup:ERROR:Channel received invalid message: Unknown encoding: null +1ms

**Comment by ibc** [comment]
Have you any problem by using the same computer and browser in https://demo.mediasoup.org? I mean, that it work for you when connecting many browsers to the same room?

**Comment by kul1010** [comment]
no issue with given url. But i want to integrate it at my localhost.

**Comment by ibc** [comment]
Then there is some kind of locale issue in your server (although I don't know how it would affect the demo app). Just try forcing UTF-8 locale.

**Comment by kul1010** [comment]
ok. i have left it due to its not based at reactjs and jssip.

**Comment by ibc** [comment]
The demo client side is based on Reactjs. Not sure why you assumed it should be also based on JsSIP.

**Comment by kul1010** [comment]
I am very confused to decide which technology will be best for video conferencing using React+Freeswitch.
Kindly Guide me.
