### ISSUE TITLE
Live demo page is 404'ing

### ISSUE THREAD

**Issue by brycepj** [versatica/mediasoup-demo#44]
Looks like https://demo.mediasoup.org/ redirects to https://test.mediasoup.org/, which is returning a 404 for me. Maybe the links in the documentation need to be updated?

**Comment by ibc** [comment]
Should be fixed now. thanks.

**Comment by ibc** [comment]
The proper domain is https://demo.mediasoup.org which must redirect to https://v3demo.mediasoup.org.
