### ISSUE TITLE
Error: Cannot find module './data/ru'

### ISSUE THREAD

**Issue by denisrocks** [versatica/mediasoup-demo#45]
The issue related to `pokemon` library. It [tries to load the language data](https://github.com/sindresorhus/pokemon/blob/f674e3763d67f1c81b90037526da94a8357bd620/index.js#L30) when the `getLocalizedList` function is called. The solution is to copy the `/node_modules/pockemon/data` to public directory when building.

**Comment by ibc** [comment]
Indeed copying that `data` directory would fix it, but I cannot spend so much time in a demo app.

Issue fixed by just allowing English names. Thanks for reporting.
