### ISSUE TITLE
cannot see remote peer

### ISSUE THREAD

**Issue by starnightcyber** [versatica/mediasoup-demo#48]
helo, there is a problem, that peer can not see the other

one can see all three, one can only see himself， like the following... 

![image](https://user-images.githubusercontent.com/19260696/56714824-8bba1a80-6768-11e9-8850-1d71f59a58f6.png)

**Comment by ibc** [comment]
Sorry, not enough info. And obviously that doesn't happen in the online demo.

**Comment by starnightcyber** [comment]
just report this kind of "phenomenon" ...

**Comment by ChenZhaobin** [comment]
@starnightcyber  Did you solved this?I come with the same problem

**Comment by ibc** [comment]
You have set RTP listen IP "0.0.0.1". You should know what that implies. BTW, have you read the API doc?

**Comment by starnightcyber** [comment]
> @starnightcyber Did you solved this?I come with the same problem

It works fine most of the time, fails occasionally。
maybe network problems or webcam。
And i found VP8 works smoothly than H.264, just report this kind of "phenomenon"...

**Comment by ibc** [comment]
> It works fine most of the time, fails occasionally。
> maybe network problems or webcam。

Have you ever seen the very same issue using the official online demo?

**Comment by starnightcyber** [comment]
Actually, I do not use the official online demo often,  network comes a bit slow, so i put it up for local test. 
And in my memory, the official online demo works fine when i use.  
I don't know why, but is just happens,  and someone else just met the same problem.

**Comment by starnightcyber** [comment]
It may be strange to you,  because it works fine with you without any problems.

**Comment by ibc** [comment]
> I don't know why, but is just happens, and someone else just met the same problem.

I don't think @ChenZhaobin has the "same" problem. He is using "0.0.0.1" as RTC `listenIp` so...

**Comment by ChenZhaobin** [comment]
I have changed 'ip' to local Ip and announcedIp to public Ip;also tried nginx 
still ,cannot see remote peer ,cannot hear remote sound. I am using ubuntu 16.04
listenIps :
			[ 
                          { ip:'172.17.59.32', announcedIp: '47.240.40.68' } 
			],

**Comment by ibc** [comment]
https://mediasoup.org/faq/#running-mediasoup-in-hosts-with-private-ip

For further questions, please use the mediasoup Discourse Group as already requested.

**Comment by ChenZhaobin** [comment]
my cloud server only have two cpu cores ,is this the reason why cannot see remote peer? @ibc

**Comment by ibc** [comment]
I'm sorry @ChenZhaobin, but I've referenced specific parts of the mediasoup API documentation and FAQ and you just don't mention anything about them.

No, your problem is not due to just having "two cpu cores". You can keep trying random hypotheses or you can read the docs.

**Comment by ChenZhaobin** [comment]
@ibc  After changing nodejs to latest version ,rebuld server folder , new error shows  up :'numStream' of undefinded
![U0KT48X3RYMJ5C%)PL BQFQ](https://user-images.githubusercontent.com/16506634/60258337-8794af80-9907-11e9-9c64-2ef75b476d32.png)

**Comment by ChenZhaobin** [comment]
maybe _mediasoupDevice.sctpCapabilities is null

**Comment by ibc** [comment]
That's a temporal bug in the demo we'll fix today. I insist, anyway, that you have not commented anything about the doc links I told you.

**Comment by ChenZhaobin** [comment]
I am a fool，
After reading the document carefully, 
I finally solved this problem by opening UDP port number 40000-49999.
Thanks for this awesome demo!
