### ISSUE TITLE
H.264 resolution do not go with spatial layer changes

### ISSUE THREAD

**Issue by starnightcyber** [versatica/mediasoup-demo#49]
if you click down|up on the right, we are suppose to see the resolution changes，
and i do see the changes before, but it just does not work now!
the following with my webcam
1280\*720    spatial layer 2
640\*360     spatial layer 1
320\*180     spatial layer 0

![image](https://user-images.githubusercontent.com/19260696/56715752-20257c80-676b-11e9-895c-3d0ad2c4cc45.png)

**Comment by ibc** [comment]
You are not using the latest version. Please upgrade the demo app and first check in the online demo app.
