### ISSUE TITLE
Error joining the room.

### ISSUE THREAD

**Issue by renozzz** [versatica/mediasoup-demo#50]
Happens on **joinRoom** request.

OS: Ubuntu 18.04

```
  mediasoup-demo-server:INFO protoo connection request [roomId:t869enme, peerId:2cygfnaf, address:192.168.1.2, origin:https://192.168.1.2:3000] +25s
  mediasoup-demo-server:Room protoo Peer "request" event [method:getRouterRtpCapabilities, peerId:2cygfnaf] +24s
  mediasoup-demo-server:Room protoo Peer "request" event [method:createWebRtcTransport, peerId:2cygfnaf] +780ms
  mediasoup:Router createWebRtcTransport() +25s
  mediasoup:Channel[pid:23101] request() [method:router.createWebRtcTransport, id:4] +25s
  mediasoup:ERROR:worker[pid:23101] RTC::PortManager::Bind() | throwing MediaSoupError: port bind failed due to address not available [udp:1.2.3.4, attempt:1] +25s
  mediasoup:WARN:Channel[pid:23101] request failed [method:router.createWebRtcTransport, id:4]: port bind failed due to address not available [udp:1.2.3.4, attempt:1] +25s
  mediasoup-demo-server:ERROR:Room request failed:Error: port bind failed due to address not available [udp:1.2.3.4, attempt:1] at Channel._processMessage (/home/renozzz/Documents/mediasoup-demo/server/node_modules/mediasoup/lib/Channel.js:284:19) at Socket.Channel._socket.on (/home/renozzz/Documents/mediasoup-demo/server/node_modules/mediasoup/lib/Channel.js:101:13) at Socket.emit (events.js:193:13) at Socket.EventEmitter.emit (domain.js:481:20) at addChunk (_stream_readable.js:295:12) at readableAddChunk (_stream_readable.js:276:11) at Socket.Readable.push (_stream_readable.js:231:10) at Pipe.onStreamRead (internal/stream_base_commons.js:150:17) +25s

```

**Comment by ibc** [comment]
Read the logs.

**Comment by bhaskarvgurram** [comment]
@Reennos were you able to figure out what the issue was ?

**Comment by ibc** [comment]
Really @bhaskarvgurram, please read the log error. It's no so hard.

**Comment by bhaskarvgurram** [comment]
> Really @bhaskarvgurram, please read the log error. It's no so hard.

port bind failed due to address not available. I would be grateful if you could guide me or give me a hint. I have been trying since yesterday to make it run. Thank you.

**Comment by ibc** [comment]
Which address is not available?

**Comment by bhaskarvgurram** [comment]
> Which address is not available?

udp:1.2.3.4

**Comment by ibc** [comment]
Ok, and probably you don't have such a "1.2.3.4" IP in your host, right?

We wrote extensive documentation for something: https://mediasoup.org/documentation/v3/mediasoup/api/#router-createWebRtcTransport

**Comment by bhaskarvgurram** [comment]
> Ok, and probably you don't have such a "1.2.3.4" IP in your host, right?
> 
> We wrote extensive documentation for something: https://mediasoup.org/documentation/v3/mediasoup/api/#router-createWebRtcTransport

Changed the WebRtcTransport listenIps in config.js. Thank you so much

**Comment by lee1994522** [comment]
> > Ok, and probably you don't have such a "1.2.3.4" IP in your host, right?
> > We wrote extensive documentation for something: https://mediasoup.org/documentation/v3/mediasoup/api/#router-createWebRtcTransport
> 
> Changed the WebRtcTransport listenIps in config.js. Thank you so much

Could you tell me what does the listenIps mean and how to set them?

**Comment by ibc** [comment]
Check the link above

**Comment by ChenZhaobin** [comment]
@bhaskarvgurram @ibc  change 1.2.3.4 to what? I have bought a cloud server  IP address:47.110.55.58; maybe it doesn't have so many local IP such as 192.168.xxx

**Comment by ibc** [comment]
Please read the doc. We write extensive doc to not have to answer the same questions many times:

* https://mediasoup.org/documentation/v3/mediasoup/api/#router-createWebRtcTransport
* https://mediasoup.org/documentation/v3/mediasoup/api/#WebRtcTransportOptions

**Comment by ChenZhaobin** [comment]
change to 0.0.0.1 solved my probem ,thanks for all of these!
