### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by HalcyonHuang** [versatica/mediasoup-demo#51]
i want to push a file to mediasoup,  but it failed:

SERVER_URL="https://192.168.137.213:3000/?info=true&throttleSecret=foo:4443" ROOM_ID=wnzexkxe  MEDIA_FILE=./test.mp4 ./ffmpeg.sh

+ echo '>>> verifying that room '\''wnzexkxe'\'' exists...'
>>> verifying that room 'wnzexkxe' exists...
+ http --check-status GET 'https://192.168.137.213:3000/?info=true&throttleSecret=foo:4443/rooms/wnzexkxe'

http: error: SSLError: HTTPSConnectionPool(host='192.168.137.213', port=3000): Max retries exceeded with url: /?info=true&throttleSecret=foo:4443/rooms/wnzexkxe (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)'),)) while doing GET request to URL: https://192.168.137.213:3000/?info=true&throttleSecret=foo:4443/rooms/wnzexkxe

how to fix this error ?

**Comment by ibc** [comment]
I'm afraid we cannot give support about basic HTTPS/TLS stuff. This is the mediasoup demo app. We just manage issues related to mediasoup and mediasoup-client. Sorry.

**Comment by sholzmayer** [comment]
Add the option `--verify=no` to the http-command. 

```
HTTPIE_COMMAND="http --verify=no --check-status"
```
