### ISSUE TITLE
websocket  ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by ChenZhaobin** [versatica/mediasoup-demo#52]
I have the same problem with 
https://github.com/versatica/mediasoup-demo/issues/28
 and below is my server start console,is something wrong?

![企业微信截图_1561538498743](https://user-images.githubusercontent.com/16506634/60165428-d839d900-9831-11e9-8819-e1bcc9ee9a06.png)
![企业微信截图_15615387044513](https://user-images.githubusercontent.com/16506634/60165437-da9c3300-9831-11e9-920b-a0a01e62eeff.png)

**Comment by ibc** [comment]
I'm sorry but this issue tracker is just for reporting issues in the demo application, not usage or mediasoup installation issues or questions. Please use the forum for that (there is a category for "mediasoup-demo"):

https://mediasoup.discourse.group/

**Comment by ChenZhaobin** [comment]
Reboot saved my problem
