### ISSUE TITLE
Cannot read property 'numStreams' of undefined at Room

### ISSUE THREAD

**Issue by avdance** [versatica/mediasoup-demo#53]
hi, I want test media-demo, but I get this error below:

"mediasoup-demo-server:ERROR:Room request failed:TypeError: Cannot read property 'numStreams' of undefined at Room._handleProtooRequest (/home/garrylea/mediasoup/mediasoup-demo/server/lib/Room.js:796:40) at Peer.peer.on (/home/garrylea/mediasoup/mediasoup-demo/server/lib/Room.js:247:9)"

How can I resolved it ?

**Comment by ibc** [comment]
Please, update, it was fixed yesterday:

https://github.com/versatica/mediasoup-demo/commit/54f80df1edb0f2041dec1778e06149cc2fbb915e#diff-71702c56d3fb89b4a04bcb3c25d69660R799

**Comment by avdance** [comment]
thanks, now it can work!
