### ISSUE TITLE
Crash on Safari: Webpage was reloaded because a problem occured

### ISSUE THREAD

**Issue by Coletex** [versatica/mediasoup-demo#58]
When I join a room with several people (around 15 people) in Safari, the webpage is crashing in about 90% of the times. This happens after allowing to use the microphone, but before allowing to use the camera. The browser console doesn't show any errors. 
In about 10% of the times, everything works perfectly. 

These are the information I found so far:
- This only happens with Safari, if I use Chrome, it's always working. 
- The crash doesn't happen if no other people are in the room.
- The crash also occurs if I deploy the demo on my server. 

Tested devices:
- Macbook Pro (2017) with MacOS 10.15 on Safari 13.0.2
- iPhone X with iOS 13.1.3 on Safari 13.0.2

Steps to reproduce:
1. Enter a room on https://v3demo.mediasoup.org/ with 15 people, e.g. by opening the same room link in 15 browser tabs in Chrome.
2. Now enter the same room with Safari on an arbitrary device.
3. Allow to use the microphone.
4. The webpage will be reloaded and the error "This webpage was reloaded because a problem occured." is shown.
5. Click on allow to use the microphone again.
6. The page is crashing completely and the error "A problem repeatedly occured with https://v3demo.mediasoup.org/?roomId=owhaa7lq".

![image](https://user-images.githubusercontent.com/16925101/67147946-1607b500-f29a-11e9-87e2-3f2be0429da1.png)

**Comment by ibc** [comment]
Crashes on Safari (or in any browser) must be reported in the corresponding browser issue tracker, not here. If the browser crashes that's not a bug of mediasoup.
