### ISSUE TITLE
How to push H264 stream with ffmpeg

### ISSUE THREAD

**Issue by funnywwh** [versatica/mediasoup-demo#60]
-HTTPIE_COMMAND="http --check-status"
+HTTPIE_COMMAND="http --check-status  --verify=no"
 AUDIO_SSRC=1111
 AUDIO_PT=100
 VIDEO_SSRC=2222
-VIDEO_PT=101
+VIDEO_PT=125
 
 #
 # Verify that a room with id ROOM_ID does exist by sending a simlpe HTTP GET. If
@@ -140,7 +140,7 @@ echo ">>> creating mediasoup video Producer..."
 ${HTTPIE_COMMAND} -v \
        POST ${SERVER_URL}/rooms/${ROOM_ID}/broadcasters/${BROADCASTER_ID}/transports/${transportId}/producers \
        kind="video" \
-       rtpParameters:="{ \"codecs\": [{ \"mimeType\":\"video/vp8\", \"payloadType\":${VIDEO_PT}, \"clockRate\":90000 }], \"encodings\": [{ \"ssrc\":${VIDEO_SSRC} }] }" \
+       rtpParameters:="{ \"codecs\": [{ \"mimeType\":\"video/H264\", \"payloadType\":${VIDEO_PT}, \"clockRate\":90000 }], \"encodings\": [{ \"ssrc\":${VIDEO_SSRC} }] }" \
        > /dev/null
 
 #
@@ -164,6 +164,6 @@ ffmpeg \
        -map 0:a:0 \
        -acodec libopus -ab 128k -ac 2 -ar 48000 \
        -map 0:v:0 \
-       -pix_fmt yuv420p -c:v libvpx -b:v 1000k -deadline realtime -cpu-used 4 \
+       -pix_fmt yuv420p -c:v libx264  -b:v 1000k -deadline realtime -cpu-used 4 \
        -f tee \
        "[select=a:f=rtp:ssrc=${AUDIO_SSRC}:payload_type=${AUDIO_PT}]rtp://${transportIp}:${transportPort}|[select=v:f=rtp:ssrc=${VIDEO_SSRC}:payload_type=${VIDEO_PT}]rtp://${transportIp}:${transportPort}"

ERROR:
http: warning: HTTP 500 unsupported codec [mimeType:video/H264, payloadType:125]

**Comment by ibc** [comment]
Sorry, this is not a support forum.
