### ISSUE TITLE
why browser always websocket connection fail when connect to my mediasoup server?

### ISSUE THREAD

**Issue by 704817030** [versatica/mediasoup-demo#61]
I　have deploy the demo in my aliyun,and I config the port of 4443,3000,3001,40000-49999. but when I open chrome browser to my mediasoup ,I can view the page ,but the browser always hint 'websocket connection fail' ,and then I can't join the meeting .

How can I solve this problem?

**Comment by jmillan** [comment]
This is not an issue. Use the [discourse group](https://mediasoup.discourse.group/c/mediasoup-demo) for this type of questions.

Read thoroughly the [README](https://mediasoup.discourse.group/c/mediasoup-demo) file and make sure you are following it.

**Comment by vrqin** [comment]
maybe need check your domain and cert config

**Comment by 704817030** [comment]
i have solve the problem. i got that it is because of the ip address in config.js。now i have done it.



---Original---
