### ISSUE TITLE
OSError: [Errno 2] No such file or directory while installation

### ISSUE THREAD

**Issue by NModern** [versatica/mediasoup-demo#65]
`

> clang-tools-prebuilt@0.1.4 postinstall /opt/mediasoup-demo/server/node_modules/clang-tools-prebuilt
> node install.js

unziping /root/.clang-tools/clang-tools-r298696-linux.tgz

> mediasoup@3.3.0-pre1 postinstall /opt/mediasoup-demo/server/node_modules/mediasoup
> node npm-scripts.js postinstall

npm-scripts.js [INFO] running task "postinstall"
npm-scripts.js [INFO] executing command: make -C worker
make: Entering directory '/opt/mediasoup-demo/server/node_modules/mediasoup/worker'
/usr/bin/python2 ./scripts/configure.py -R mediasoup-worker
Traceback (most recent call last):
  File "./scripts/configure.py", line 83, in <module>
    (major, minor), is_clang = compiler_version()
  File "./scripts/configure.py", line 36, in compiler_version
    proc = subprocess.Popen(CC.split() + ['--version'], stdout=subprocess.PIPE)
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
make: *** [Makefile:24: default] Error 1
make: Leaving directory '/opt/mediasoup-demo/server/node_modules/mediasoup/worker'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mediasoup@3.3.0-pre1 postinstall: `node npm-scripts.js postinstall`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mediasoup@3.3.0-pre1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-13T10_36_13_086Z-debug.log

`

**Comment by ibc** [comment]
So you just paste the error output but do not even tell which OS, GCC, etc versions you are using. Sorry, cannot help that way.

**Comment by NModern** [comment]
I have fresh install of Centos 8
installed python 2.7
gcc-8.2.1-3.5.el8.x86_64
GNU Make 4.2.1

What other information needed?

**Comment by ibc** [comment]
Node and NPM version.

BTW please clone the mediasoup repo, enter it, checkout the "devel" branch and run `npm install` and let's see what happens.

**Comment by NModern** [comment]
error: pathspec 'devel' did not match any file(s) known to git.

**Comment by NModern** [comment]
ok I get it. Now cloning mediasoup repo.

**Comment by NModern** [comment]
> Node and NPM version.
> 
> BTW please clone the mediasoup repo, enter it, checkout the "devel" branch and run `npm install` and let's see what happens.

mediasoup installed without any errors.

**Comment by ibc** [comment]
Are you sure you got the "devel" branch from gitHub?

**Comment by NModern** [comment]
[root@localhost opt]# git clone --single-branch --branch devel https://github.com/versatica/mediasoup.git
Cloning into 'mediasoup'...
remote: Enumerating objects: 919, done.
remote: Counting objects: 100% (919/919), done.
remote: Compressing objects: 100% (597/597), done.
remote: Total 42972 (delta 482), reused 581 (delta 235), pack-reused 42053
Receiving objects: 100% (42972/42972), 150.41 MiB | 4.13 MiB/s, done.
Resolving deltas: 100% (27867/27867), done.
Checking out files: 100% (9196/9196), done.
[root@localhost opt]# cd mediasoup
[root@localhost mediasoup]# npm install
npm WARN deprecated fsevents@1.2.9: One of your dependencies needs to upgrade to fsevents v2: 1) Proper nodejs v10+ support 2) No more fetching binaries from AWS, smaller package size
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()

> clang-tools-prebuilt@0.1.4 postinstall /opt/mediasoup/node_modules/clang-tools-prebuilt
> node install.js

unziping /root/.clang-tools/clang-tools-r298696-linux.tgz
npm WARN lifecycle mediasoup@3.3.0-pre1~postinstall: cannot run in wd mediasoup@3.3.0-pre1 node npm-scripts.js postinstall (wd=/opt/mediasoup)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 987 packages from 572 contributors and audited 883871 packages in 23.852s
found 0 vulnerabilities


Something wrong here?

**Comment by ibc** [comment]
Everything looks good there. No idea why it fails for you when in mediasoup-demo. Note however that, currently, mediasoup-demo project uses both mediasoup and mediasoup-client "devel" branches with a `git` URL in their `package.json` files. Not sure if related.

**Comment by NModern** [comment]
After installing correct gcc  and g++ mediasoup-demo installed normally. Now going to run it. 

Big thanks to you. I think I couldn't get it out without your help.

**Comment by ibc** [comment]
So you did not install g++ before when it failed, right?

**Comment by NModern** [comment]
Yeah. Can you write dependencies in README (For example: python 2.7, GCC, G++). So the ones who install such things for the first time like me to know what's needed. Because errors are not always informative.

**Comment by ibc** [comment]
I've done it:

https://github.com/versatica/mediasoup-demo#installation

**Comment by NModern** [comment]
Thanks.
