### ISSUE TITLE
Chrome of low version can not work

### ISSUE THREAD

**Issue by shenjiesky** [versatica/mediasoup-demo#68]
Dear authors:
    I use chrome of low version to join the room, and got some errors.I suspect that the compiled file does not support the lower version of the browser kernel.Can you compile a version to solve this problem. Thank you very much.
![142141574840698_ pic](https://user-images.githubusercontent.com/7973743/69704710-eff1f200-112e-11ea-9686-67c306137f19.jpg)
![142151574840698_ pic](https://user-images.githubusercontent.com/7973743/69704726-faac8700-112e-11ea-8330-7460cf6445cd.jpg)
![142161574840698_ pic_hd](https://user-images.githubusercontent.com/7973743/69704739-026c2b80-112f-11ea-98d6-72d909e03b4d.jpg)

**Comment by ibc** [comment]
No, sorry. It's just a demo.
