### ISSUE TITLE
Failed at mediasoup@3.3.7 postinstall script

### ISSUE THREAD

**Issue by devWaleed** [versatica/mediasoup-demo#69]
I just cloned this repository yesterday and did npm install in server and app. Server is giving me the following error:

Unexpected end of json input while parsing near '...E+\nbd...'

Failed at mediasoup@3.3.7 postinstall script

I am running it on Ubuntu 18.04 using KMS 6.12.*

**Comment by ibc** [comment]
Try again please (mediasoup 3.3.8 is out although it fixes a completely unrelated thing).

**Comment by ibc** [comment]
Confirmed that the issue does not happen with mediasoup 3.3.8. I also doubt it happened in 3.3.7. I don't know your Node version, etc. And given that you tried to install the mediasoup-demo to test something related with Kurentu... it's clear for me that you did not read the requirements for installing mediasoup. Closing.

**Comment by webkitt** [comment]
I am currently having this issue. I did complete the environtment variables and installation of Python2.
Visual Studio 2019 - GYP_MSVS_VERSION: "2019".  There is no MSBuild.exe close to where the example path provided but it is at this location on my system: "C:\Windows\Microsoft.NET\Framework64\v4.0.30319"

**Comment by ibc** [comment]
Read the mediasoup GitHub issues. This is just the demo app.
