### ISSUE TITLE
firewall permissions

### ISSUE THREAD

**Issue by christian-2** [versatica/mediasoup-demo#71]
I have the mediasoup demo installed currently with `MEDIASOUP_MIN/MAX_PORT` as 40000/40003. The server runs successfully and the app appears in the browser, but there is no actual connectivity between the two components yet ("WebSocket connection failed"). What are the exact minimum requirements in terms of firewall permissions (between app and server; ports for UDP and TCP) in my case?

**Comment by ibc** [comment]
Please use the mediasoup Discourse Group forum for questions
