### ISSUE TITLE
WebSocket Connection Failed

### ISSUE THREAD

**Issue by sajidjutt7** [versatica/mediasoup-demo#76]
I am running app and getting this error continuously in chrome browser.
Initiating this app using
> npm start

This is output in browser. Please guide me how to make it work

<img width="1395" alt="Screenshot 2020-03-09 at 5 09 41 PM" src="https://user-images.githubusercontent.com/20970229/76212108-8e5f1a80-6229-11ea-8681-bba89d30a097.png">

**Comment by ibc** [comment]
No sorry, no support about the mediasoup demo in GitHub. Use the mediasoup public forum to get help and provide much more information (such as whether you are using proper TLS certificates or not).
