### ISSUE TITLE
mediasoup-demo-server:ERROR 

### ISSUE THREAD

**Issue by 1309954466** [versatica/mediasoup-demo#77]
mediasoup-demo-server:ERROR room creation or room joining failed:TypeError: mediasoupRouter.createPlainTransport is not a function at Function.create (/home/wch/mediasoup-demo/server/lib/Bot.js:16:43) at Function.create (/home/wch/mediasoup-demo/server/lib/Room.js:74:25)     at processTicksAndRejections (internal/process/task_queues.js:97:5) at async getOrCreateRoom (/home/wch/mediasoup-demo/server/server.js:469:10) at async Object.execute (/home/wch/mediasoup-demo/server/server.js:426:17)

thank you!!!!

**Comment by 1309954466** [comment]
Ubuntu 18.04.4 LTS Local environment

**Comment by ibc** [comment]
Sorry, no. Update deps. Read the mediasoup documentation. This was announced.
