### ISSUE TITLE
broadcasters/ffmpeg.sh returns HTTP 400 missing listenIp

### ISSUE THREAD

**Issue by zyzniewski** [versatica/mediasoup-demo#78]
Hi,
just wanted to test FFmpeg broadcasting on v3demo.mediasoup.org but I get "HTTP 400 missing listenIp" error while firing `POST ${SERVER_URL}/rooms/${ROOM_ID}/broadcasters/${BROADCASTER_ID}/transports` request.
Tried to include `listenIp` param but it seems to be ignored by the server https://github.com/versatica/mediasoup-demo/blob/v3/server/server.js#L227 and loaded from the config https://github.com/versatica/mediasoup-demo/blob/v3/server/lib/Room.js#L477 - example config includes it https://github.com/versatica/mediasoup-demo/blob/v3/server/config.example.js#L138

**Comment by ibc** [comment]
The demo deployment was not updated. Fixed. Thanks.
