### ISSUE TITLE
Wrong constraint?

### ISSUE THREAD

**Issue by havfo** [versatica/mediasoup-demo#79]
https://github.com/versatica/mediasoup-demo/blob/5dd74deb310af967db92b5c89ffd0c8db2644bff/app/lib/RoomClient.js#L1245

Shouldn't this contraint be `frameRate`?

Ref: [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/API/MediaTrackConstraints/frameRate)

**Comment by ibc** [comment]
Maybe, not sure.

Anyway, please use the mediasoup public forum for questions about mediasoup or about the mediasoup-demo project.

Or, if you are really sure that it should be `frameRate` instead (and you have tested it), a PR is welcomed.
