### ISSUE TITLE
node server.js error

### ISSUE THREAD

**Issue by mangdehuang** [versatica/mediasoup-demo#83]
i install  server.then node ser.js

mediasoup-demo-server:INFO running 4 mediasoup Workers... +0ms
  mediasoup:ERROR:Worker worker process failed [pid:undefined]: spawn D:\code\gitee\build-react\build-react\mediasoup\mediasoup-demo-3\server\node_modules\_mediasoup@3.5.6@mediasoup\worker\out\Release\mediasoup-worker ENOENT +0ms
(node:1772) UnhandledPromiseRejectionWarning: Error: spawn D:\code\gitee\build-react\build-react\mediasoup\mediasoup-demo-3\server\node_modules\_mediasoup@3.5.6@mediasoup\worker\out\Release\mediasoup-worker ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled
will terminate the Node.js process with a non-zero exit code.

who can help me

**Comment by ibc** [comment]
Not here, please. Use the mediasoup forum for support/questions.
