### ISSUE TITLE
Video Stream stop with broadcaster

### ISSUE THREAD

**Issue by whatisor** [versatica/mediasoup-demo#89]
1. Open web client
2. Run ffmpeg broadcaster with ffmpeg and h264 ( confirm that broadcaster keep loggin without issue)
3. Observe video stream from broadcaster, after a while(10-20s) stream is freeze, but broadcaster keep normal logging without any error.
4. Obseve server log, without any error event.
5. Observe wen client log, at the time when video just freezed, found these:
mediasoup-demo:RoomClient proto "notification" event [method:consumerScore, data:{consumerId: "ca3b1abf-ad98-4ac2-8af7-8198ebbfeba6", score: {…}}] +26ms

It seems to try to create new consumer?

**Comment by ibc** [comment]
Please, use the forum for questions.
