### ISSUE TITLE
Error during WebSocket handshake

### ISSUE THREAD

**Issue by zhangzhx666** [versatica/mediasoup-demo#9]
WebSocket connection to 'wss://xxx.xxx.xxx.xxx:3443/' failed: Error during WebSocket handshake: Unexpected response code: 400.
Clear chrome histroy ,reopen chrome. The above error message disappears,connect ok.

**Comment by jmillan** [comment]
Issue tracker is for library issues, not for usage issues.

Please use the mailing list.
