### ISSUE TITLE
Overconstrained error when using webcam in some browsers and networks 

### ISSUE THREAD

**Issue by cfeeney5** [versatica/mediasoup-demo#90]
## Recreate
Ubuntu 18.04 Chrome Version 81.0.4044.113 (Official Build) (64-bit) 
Run demo https://v3demo.mediasoup.org/
Try enabling webcam 

## Result
Error enabling webcam [object overconstrained error]. Webcam is not  enabled

## Comments
This error does not appear if the demo is ran on a localhost. I think its possibly some security issue related to not providing the exact deviceId when its ran remotely.  

## Possible solution 

If [line 964 of the roomClient](https://github.com/versatica/mediasoup-demo/blob/bf0916329bbeb27e3923e9601f4d39e3d0fbca22/app/lib/RoomClient.js#L964) is changed to ideal rather than exact the issue is resolved.

**Comment by ibc** [comment]
Done. Next time, if possible, please send a PR.
