### ISSUE TITLE
transport.consume() called with an extra param codecOptions

### ISSUE THREAD

**Issue by milen-yordanov** [versatica/mediasoup-demo#91]
See: https://github.com/versatica/mediasoup-demo/blob/v3/app/lib/RoomClient.js#L341
See: https://mediasoup.org/documentation/v3/mediasoup-client/api/#ConsumerOptions

There is no codecOptions in  ConsumerOptions. Looks like codecOptions should be removed from the call below.

```
const consumer = await this._recvTransport.consume(
{
	id,
	producerId,
	kind,
	rtpParameters,
	codecOptions,
	appData : { ...appData, peerId } // Trick.
});
```

**Comment by ibc** [comment]
Done.
