### ISSUE TITLE
Showing participants` video doesn`t work after hiding it

### ISSUE THREAD

**Issue by stasoft91** [versatica/mediasoup-demo#93]
Showing participants' video doesn`t work after hiding it. 
Most probably because the only place of setting device cookie is in Me.jsx by button.

**Comment by ibc** [comment]
I don't know what you mean, but I don't want to discuss mediasoup-demo improvements here in GitHub. Please explain it in the mediasoup public forum (there is a "mediasoup-demo" category there) and describe the issue in more detail.
